Naive handling for online video links
IguanasInPyjamas/Iggy-Player pull request #8
Opened 2020-12-20 17:01 UTC by IguanasInPyjamas

Works on links to the direct file. Doesn't handle youtube. Should we consider adding youtube-dl for those types of problems @MattAG

2020-12-20 17:01 UTC, IguanasInPyjamas commented on src/main.rs
> +    if path.contains("https"){
the naivety comes here, not all websites are https.

2020-12-20 17:04 UTC, MattAG commented
> Works on links to the direct file. Doesn't handle youtube. Should we consider adding youtube-dl for those types of problems @MattAG 

Which URLs have you tried with Youtube?

2020-12-20 17:04 UTC, MattAG commented on src/main.rs
> +    if path.contains("https"){
Should, at the very least, also allow http.

2020-12-20 20:25 UTC, IguanasInPyjamas commented on src/main.rs
> +    if path.contains("https"){
On it

2020-12-20 20:26 UTC, IguanasInPyjamas commented
> > Works on links to the direct file. Doesn't handle youtube. Should we consider adding youtube-dl for those types of problems @MattAG
> 
> Which URLs have you tried with Youtube? i.e. Have you tried embed links too?

Well, it's more that I know it probably won't work, As a YouTube link isn't linking only to the video. I'll test it though

2020-12-20 23:27 UTC, MattAG commented
A quick search makes it look possible but it might require a GStreamer plugin.

2020-12-21 05:39 UTC, IguanasInPyjamas commented on src/main.rs
> +    if path.contains("https"){
Done

2020-12-21 05:41 UTC, IguanasInPyjamas commented
> A quick search makes it look possible but it might require a GStreamer plugin.

It's good to think about for the future.

Also, @MattAG , I've restructured the file system as well as adding queuing, it works well but shuffle / loop needs to be implemented. Let me know your thoughts

2020-12-21 10:04 UTC, MattAG commented
Added more comments now. I'm basically running off the rule that functions should be ~25 lines max. Obviously, there can be exceptions to this, where it makes sense, but it's a decent rule of thumb. If a function only does one thing, it can be unit tested.

2020-12-21 10:51 UTC, MattAG requested changes

2020-12-21 10:53 UTC, IguanasInPyjamas commented on src/main.rs
> +            player::player_loop(new_arg);
It destroys and then creates a new player yes, I need to experiment some more with uri properties to see if a more elegant solution can be found

2020-12-21 10:56 UTC, IguanasInPyjamas commented on src/main.rs
> +            let new_arg:Vec<String> = vec![args[0].clone(),args[i].clone()];
100%

2020-12-21 13:21 UTC, MattAG approved these changes
Gj

2020-12-21 13:22 UTC, merged